---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ankit/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r childs_images $DEPLOYPATH  # Add this line to copy the images directory
